services:
  - type: web
    name: saha-crm-sistemi
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true

      - key: DATABASE_URL
        fromDatabase:
          name: saha-crm-db
          property: connectionString

databases:
  - name: saha-crm-db
    databaseName: sahacrm
    user: sahacrm
    plan: free
